/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.jupiter.api.Test;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.assertTrue;


class AppTest {
    @Test
    public void testApplyTransform() throws IOException {
        Bitmap bitmap = null;
        bitmap = new Bitmap("baldy-8bit.bmp");

        bitmap.applyTransform("invert");

        try {
            bitmap.writeToFile("/Users/dashalewis/projects/courses/code-401-java/bitmap/bitmap-transformer/Output2/OutputFile.bmp");
        } catch(IOException e){
            System.out.println("Error Writing Test Image: " + e.getMessage());
        }

        BufferedImage expected = null;
        BufferedImage actual = null;

        try{
            actual = ImageIO.read(new File("/baldy-8bit.bmp"));
            expected = ImageIO.read(new File("/Output2/OutputFile.bmp"));
        } catch(IOException e){
            System.out.println("Error Loading Actual Output Image: " + e.getMessage());
        }

        assertTrue(imagesEqual(expected, actual));
    }

    private boolean imagesEqual(BufferedImage img1, BufferedImage img2){
        return true;

    }
}
